---
name: Build and Deploy CV to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra
          pdflatex -interaction=nonstopmode cv.tex
          pdflatex -interaction=nonstopmode cv.tex

      - name: List files after LaTeX compilation
        run: ls -R

      - name: Create content for GitHub Pages
        run: |
          mkdir public
          cp cv.pdf public/
          cp sign.png public/ 
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>My CV</title>
            <style>
              body { margin: 0; padding: 0; }
              embed { display: block; width: 100%; height: 100vh; }
            </style>
          </head>
          <body>
            <embed src="cv.pdf" type="application/pdf" />
            <p>If the PDF doesn't load, <a href="cv.pdf">download it here</a>.</p>
          </body>
          </html>
          EOF
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
